/* CREATION DES INDEX SPATIAL */
/* Enregistrer comme spatial */

INSERT INTO USER_SDO_GEOM_METADATA
(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES ( 
    'ARRONDISSEMENT',    
    'DELIMITATION',    
    SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('x', -180, 180, 0.00001),        SDO_DIM_ELEMENT('y', -90, 90, 0.00001)
    ),    
    4326
);


INSERT INTO USER_SDO_GEOM_METADATA
(TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES (
    'MAISON',                 
    'LOCALISATION',           
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('x', -180, 180, 0.00001),
        SDO_DIM_ELEMENT('y', -90, 90, 0.00001) 
    ),
    4326
);


CREATE INDEX IDX_ARRONDISSEMENT
ON ARRONDISSEMENT(DELIMITATION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX IDX_MAISON_LOCALISATION
ON MAISON(LOCALISATION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;